ARG DEBIAN_FRONTEND=noninteractive
FROM raychorn/ubuntu_python38

ENV APP_PATH=/workspaces/python-firebase-sample1

LABEL version="1.0"
LABEL maintaner="Ray C Horn (raychorn@gmail.com)"
LABEL release-date="10-28-2020"
LABEL promoted="true"

